### ISSUE TITLE
Unrecognized Command: "Connected Components Labeling"

### ISSUE THREAD

**Issue by mtk27** [MontpellierRessourcesImagerie/imagej_macros_and_scripts#6]
I am trying to run the MRI_g_ratio_Tools and I continue to get this error code when running the outer boarder recognition step ("f").  I haven't edited the source code for the plug-in but I have tried saving the plugin (grow-regions) and macro (MRI...) in different folders, assuming Fiji isn't reading the files correctly.  I don't fully understand the error so I am unsure how to solve.  Any recommendations are greatly appreciated.  Debug window attached here.

[Debug_Connected Components Labeling.csv](https://github.com/MontpellierRessourcesImagerie/imagej_macros_and_scripts/files/7163071/Debug_Connected.Components.Labeling.csv)

Thanks!

**Comment by volker-baecker** [comment]
Hi @mtk27,
please have a look at the "Getting started" section of the documentation at:
https://github.com/MontpellierRessourcesImagerie/imagej_macros_and_scripts/wiki/MRI_g_ratio_Tools

The error you encounter is there because you do not have MorpholibJ installed. Please follow the instructions at:
https://imagej.net/plugins/morpholibj#installation

You should put the file MRI_g-ratio_tools.ijm into the folder macros/toolsets of yourFIJI and the file grow_regions.jar into the folder plugins of your FIJI (if the jar is not found the tool should still work, but much slower).

Please let me know if this solves the problem.

Best,
Volker

**Comment by mtk27** [comment]
Thanks so much!!  That was the issue.  
In trouble shooting something else I had uninstalled and reinstalled Fiji but forgot to add this plugin again.
